'use client';
import {useEffect,useRef,useState} from 'react';
import {Download,Layers,ArrowUpRight,Box,Maximize,Minimize,Minus,Plus,RotateCcw,Play,Pause,TreePine,MousePointer2} from 'lucide-react';
import {Popover,PopoverTrigger,PopoverContent} from '@/components/ui/popover';
import RenovationControls from './renovation-controls';
import {renovations,renovationState,type RenovationState,type RenovationId} from '@/lib/house-model/renovation-data';
import ExperienceControls from './experience-controls';
import {places,initialExperience,type Presence} from '@/lib/house-model/experience-data';
import MobileModelControls from './mobile-controls';
import {Choice} from '../panels';
import {viewpoints,regions,sourceNotes,photoChecks,type Level,type Region,type Viewpoint} from '@/lib/house-model/site-data';
import {interiorRooms} from '@/lib/house-model/interior-data';
import {planPoint,UPPER_PLAN_X_OFFSET} from '@/lib/house-model/site-data';
import type {TextureStatus} from '@/lib/house-model/photo-sources';
import type {HouseViewer} from '@/lib/house-model/viewer';

export default function HouseModel({onNavigate}:{onNavigate:(id:string)=>void}){
 const host=useRef<HTMLDivElement>(null),shell=useRef<HTMLDivElement>(null),api=useRef<HouseViewer|null>(null);
 const [experience,setExperience]=useState(initialExperience),[pendingPlace,setPendingPlace]=useState<Presence|null>(null);
 const [quality,setQuality]=useState('natural'),[textures,setTextures]=useState<TextureStatus>('idle');
 const savedCamera=useRef<ReturnType<HouseViewer['snapshot']>|null>(null);
 useEffect(()=>{if(new URLSearchParams(window.location.search).get('quality')==='realism')setQuality('realism');},[]);
 const chooseQuality=(value:string)=>{if(value===quality)return;savedCamera.current=api.current?.snapshot()||null;setTextures('idle');setQuality(value);const url=new URL(window.location.href);if(value==='realism')url.searchParams.set('quality','realism');else url.searchParams.delete('quality');window.history.replaceState(null,'',url);};
 const [mobile,setMobile]=useState(false),[interacted,setInteracted]=useState(false);
 useEffect(()=>{const query=window.matchMedia('(max-width: 767px), (max-width: 950px) and (max-height: 500px)');const update=()=>setMobile(query.matches);update();query.addEventListener('change',update);return()=>query.removeEventListener('change',update);},[]);
 const [changes,setChanges]=useState<RenovationState>(()=>renovationState()),[renovationsOpen,setRenovationsOpen]=useState(false);
 useEffect(()=>{const ids=new URLSearchParams(window.location.search).get('renovations')?.split(',')||[];if(ids.length)setChanges(previous=>Object.fromEntries(Object.entries(previous).map(([id,value])=>[id,value||ids.includes(id)])) as RenovationState);},[]);
 const activeCount=Object.values(changes).filter(Boolean).length;
 const [roomId,setRoomId]=useState('overview'),[ready,setReady]=useState(false),[failed,setFailed]=useState(false),[attempt,setAttempt]=useState(0),[level,setLevel]=useState<Level>('exterior'),[view,setView]=useState<Viewpoint>('courtyard'),[trees,setTrees]=useState(true),[rotating,setRotating]=useState(false),[expanded,setExpanded]=useState(false),[region,setRegion]=useState<Region>('main');
 useEffect(()=>{let cancelled=false;setReady(false);setFailed(false);import('@/lib/house-model/viewer').then(({createHouseViewer})=>{if(cancelled||!host.current)return;try{api.current=createHouseViewer(host.current,setRegion,()=>setReady(true),()=>setFailed(true),quality==='realism',setTextures,setExperience);if(savedCamera.current)api.current.restore(savedCamera.current);}catch{setFailed(true);}}).catch(()=>{if(!cancelled)setFailed(true);});return()=>{cancelled=true;api.current?.dispose();api.current=null;};},[attempt,quality]);
 useEffect(()=>{api.current?.setRenovations(changes);},[ready,changes]);
 useEffect(()=>{api.current?.setLevel(level);},[ready,level]);
 useEffect(()=>{api.current?.setTrees(trees);},[ready,trees,level]);
 useEffect(()=>{api.current?.setRotate(rotating);},[ready,rotating]);
 useEffect(()=>{if(!expanded&&!mobile)return;const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')setExpanded(false);};const before=document.body.style.overflow;document.body.style.overflow='hidden';window.addEventListener('keydown',onKey);return()=>{document.body.style.overflow=before;window.removeEventListener('keydown',onKey);};},[expanded,mobile]);
 const choosePlace=(p:Presence)=>{setInteracted(true);setRotating(false);setRoomId('overview');if(level!=='exterior'){setPendingPlace(p);setLevel('exterior');}else api.current?.experience?.presence(p);};
 useEffect(()=>{if(pendingPlace&&level==='exterior'){api.current?.experience?.presence(pendingPlace);setPendingPlace(null);}},[pendingPlace,level]);
 const chooseView=(v:Viewpoint)=>{setRoomId('overview');setView(v);api.current?.view(v);};
 const chooseLevel=(v:string)=>{const l=v as Level;setRoomId('overview');setLevel(l);setRotating(false);if(l!=='exterior'){setView('top');api.current?.setLevel(l);api.current?.view('top');}else{setView('courtyard');api.current?.setLevel(l);api.current?.view('courtyard');}};
 const room=interiorRooms.find(r=>r.id===roomId);
 const chooseRoom=(id:string)=>{setRoomId(id);setRotating(false);if(id==='overview'){api.current?.view('top');return;}const r=interiorRooms.find(r=>r.id===id);if(!r)return;const [x,z]=planPoint(...r.center);api.current?.focus(x+(r.level==='upper'?UPPER_PLAN_X_OFFSET:0),z,r.level==='upper'?3.4:r.level==='basement'?-2:.4,r.span);};
 const focusRenovation=(id:RenovationId)=>{setChanges(previous=>({...previous,[id]:true}));const r=renovations.find(item=>item.id===id)!;setRenovationsOpen(false);setRotating(false);setRoomId('overview');if(id==='front'||id==='solar'){chooseLevel('exterior');chooseView(id==='solar'?'east':'arrival');}else{setLevel('ground');api.current?.setLevel('ground');setView(r.view);api.current?.focus(r.center[0],r.center[1],.5,r.span);}};
 const selected=regions[region];
 return <div className="house-model-page">
  <div className="model-page-heading"><div><span className="eyebrow">REITWEG 25 · A SPATIAL STUDY</span><h1>The house, in three dimensions.</h1></div><p>The house today. The possibilities ahead.<br/>Explore your renovations together.</p></div>
  <div ref={shell} className={'model-shell'+(expanded?' is-expanded':'')}>
   <div className="model-toolbar"><div className="model-renovation-toolbar"><Popover open={renovationsOpen} onOpenChange={setRenovationsOpen}><PopoverTrigger className="model-renovation-trigger"><Layers size={18}/>Renovations<span>{activeCount||'+'}</span></PopoverTrigger><PopoverContent align="start" className="model-renovation-popover"><RenovationControls value={changes} onChange={setChanges} onFocus={focusRenovation} level={level} ready={ready&&!failed}/><button className="renovation-done" onClick={()=>setRenovationsOpen(false)}>Back to the house</button></PopoverContent></Popover><span className="model-design-status" aria-live="polite">{activeCount?`${activeCount} renovation${activeCount===1?'':'s'} on`:'Original house'}<small>{quality==='realism'?'Detailed realism':'Natural materials'}</small></span></div><div className="model-toolbar-right"><Choice label="Visual detail" value={quality} onChange={chooseQuality} items={[{id:'natural',label:'Natural materials'},{id:'realism',label:'Detailed realism'}]}/><Choice label="Choose floor" value={level} onChange={chooseLevel} items={[{id:'exterior',label:'Exterior · roofs on'},{id:'ground',label:'Ground floor'},{id:'upper',label:'Upper floor'},{id:'basement',label:'Basement'}]}/><button className="model-icon" aria-label="Save 4K image" title="Save 4K image" disabled={!ready||failed} onClick={()=>api.current?.saveImage()}><Download size={18}/></button><button className="model-icon" aria-label={expanded?'Exit expanded view':'Expand 3D view'} title={expanded?'Exit expanded view':'Expand 3D view'} onClick={()=>setExpanded(!expanded)}>{expanded?<Minimize size={19}/>:<Maximize size={19}/>}</button></div></div>
   {level!=='exterior'&&<div className="model-room-toolbar"><span className="mini-label">LOOK INSIDE</span><Choice label="Explore a room" value={roomId} onChange={chooseRoom} items={[{id:'overview',label:'Whole floor'},...interiorRooms.filter(r=>r.level===level).map(r=>({id:r.id,label:r.label}))]}/><span>Choose a room to move closer</span></div>}
   <div className="model-canvas-wrap"><ExperienceControls api={api.current} state={experience} ready={ready&&!failed} realistic={quality==='realism'} onEnable={()=>chooseQuality('realism')} onPlace={choosePlace}/><div ref={host} className="model-canvas" onPointerDown={()=>setInteracted(true)}/>{!ready&&!failed&&<div className="model-loading" role="status"><Box size={32}/><span>{quality==='realism'?'Building the detailed house…':'Assembling the house…'}</span></div>}{failed&&<div className="model-error" role="alert"><h3>The 3D view couldn’t start.</h3><p>Try reloading the model, or open the original plans below.</p><button className="btn" onClick={()=>setAttempt(attempt+1)}>Reload model</button><button className="text-btn" onClick={()=>onNavigate('plans')}>Open the plans</button></div>}
    <div className="model-tools"><button className="model-icon" aria-label="Zoom in" title="Zoom in" disabled={!ready||failed} onClick={()=>api.current?.zoom(1.2)}><Plus size={18}/></button><button className="model-icon" aria-label="Zoom out" title="Zoom out" disabled={!ready||failed} onClick={()=>api.current?.zoom(.83)}><Minus size={18}/></button><button className="model-icon" aria-label="Reset camera" title="Reset camera" disabled={!ready||failed} onClick={()=>chooseView(level==='exterior'?'courtyard':'top')}><RotateCcw size={18}/></button><button className="model-icon" aria-label={rotating?'Pause rotation':'Rotate model'} title={rotating?'Pause rotation':'Rotate model'} aria-pressed={rotating} disabled={!ready||failed} onClick={()=>setRotating(!rotating)}>{rotating?<Pause size={18}/>:<Play size={18}/>}</button><button className="model-icon" aria-label={trees?'Hide trees':'Show trees'} title={trees?'Hide trees':'Show trees'} aria-pressed={trees} disabled={level!=='exterior'} onClick={()=>setTrees(!trees)}><TreePine size={18}/></button></div>
    {experience.presence==='overview'&&<div className="model-help"><MousePointer2 size={14}/><span>{quality==='realism'&&textures==='loading'?'Loading materials from your photos…':quality==='realism'&&textures==='partial'?'Some photo materials unavailable · refresh to retry':'Drag to orbit · scroll or pinch to zoom'}</span></div>}<div className="model-north">N <span>↑</span><small>Plan north</small></div>
   </div>
   {mobile&&<MobileModelControls presenceLabel={experience.presence==='overview'?undefined:places[experience.presence].label} onSave={()=>api.current?.saveImage()} quality={quality} onQuality={chooseQuality} textures={textures} level={level} changes={changes} onChanges={setChanges} onRenovationFocus={focusRenovation} roomId={roomId} room={room} view={view} trees={trees} rotating={rotating} ready={ready&&!failed} interacted={interacted} onBack={()=>onNavigate('studio')} onLevel={chooseLevel} onRoom={chooseRoom} onView={chooseView} onTrees={()=>setTrees(!trees)} onRotate={()=>setRotating(!rotating)} onZoom={n=>api.current?.zoom(n)} onReset={()=>chooseView(level==='exterior'?'courtyard':'top')}/>}
   <div className="model-viewbar" aria-label="Camera views">{Object.entries(viewpoints).filter(([id])=>quality==='realism'||!['garden','poolside'].includes(id)).map(([id,v],i)=><button key={id} className={!room&&view===id?'selected':''} aria-pressed={!room&&view===id} disabled={!ready||failed} onClick={()=>chooseView(id as Viewpoint)}><span>0{i+1}</span>{v.label}</button>)}</div>
  </div>
  {room&&<section className="model-room-evidence"><div><span className="mini-label">EXISTING FURNITURE · PHOTO STUDY</span><h2>{room.label}</h2><p>{room.detail}</p><small>{room.note||'Recognizable pieces and their arrangement follow the photos; furniture sizes are approximate.'}</small></div><div className="model-room-photos">{room.photos.map((src,i)=><a key={src} href={src} target="_blank" rel="noreferrer"><img src={src} alt={`${room.label} — original reference ${i+1}`} loading="lazy"/><span>Reference {i+1} ↗</span></a>)}</div></section>}
  <div className="model-bottom"><section className="model-explore" aria-label="Explore the model"><span className="mini-label">EXPLORE THE PROPERTY</span><div className="model-region-list">{Object.entries(regions).map(([id,item])=><button key={id} className={region===id?'selected':''} aria-pressed={region===id} onClick={()=>{setRegion(id as Region);chooseView(id==='grounds'?'estate':id==='kitchen'?'arrival':id==='main'?'east':'courtyard');}}>{item.title}</button>)}</div></section><section className="model-selection" aria-live="polite"><h2>{selected.title}</h2><p>{selected.detail}</p><div className="button-row"><a className="text-btn" href={'/assets/'+selected.source} target="_blank" rel="noreferrer">See the source plan <ArrowUpRight size={15}/></a>{selected.renovation&&<button className="text-btn" onClick={()=>onNavigate(selected.renovation!)}>Explore this renovation <ArrowUpRight size={15}/></button>}</div></section></div>
  <details className="model-sources"><summary>How this model relates to the real house</summary><div><div className="model-photo-checks">{photoChecks.map(photo=><a key={photo.file} href={'/assets/'+photo.file} target="_blank" rel="noreferrer"><img loading="lazy" src={'/assets/'+photo.file} alt={photo.label}/><span>{photo.label} ↗</span></a>)}</div><p>Detailed realism adds photo-led joinery, curtains and ceilings, individual tiles and leaves, timber, stone and fabric textures, changing light and eye-level views. “Be here” includes progressive path-traced photographs, panoramas, films and textured model export. It uses the same plan-based geometry. Small construction details, plant species and material relief are interpretations; this is not a laser scan or a measured digital twin.</p><ul>{sourceNotes.map(note=><li key={note}>{note}</li>)}</ul><div className="button-row"><a href="/assets/expose.pdf#page=18" target="_blank" rel="noreferrer">Original exposé ↗</a><a href="/assets/house-model-source-notes.json" target="_blank" rel="noreferrer">Model assumptions ↗</a><a href="https://x.com/techartist_/status/2102503719762018434?s=20" target="_blank" rel="noreferrer">Visual inspiration ↗</a></div></div></details>
 </div>;
}
