import {gardenKitchen,firesideCourtyard,gardenKitchenBrief,firesideCourtyardBrief} from './focused-renovation-concepts';
import {courtyardIsometricConcepts} from './courtyard-concepts';
import {kitchenVolumeConcepts,kitchenVolumeBrief} from './kitchen-volume-concepts';
import newCatalog from './new-photo-catalog.json';
export const projects = [
 {id:"east",short:"East façade",title:"The east façade",summary:"A closer connection to the landscape.",image:"/assets/IMG_1403.jpg",alt:"The existing east-facing timber façade and garden",intentTitle:"A room without an edge.",intent:"Replace the rhythm of small openings and solid wall with generous, full-height glass. Keep the roof, the warmth of timber, and the strong architectural lines. Let the garden become part of every room.",photos:["IMG_1403","IMG_1405","IMG_1407","IMG_1457","IMG_1461","IMG_1462","IMG_1467","IMG_1469","IMG_1472","IMG_1473","IMG_1451","IMG_1454"]},
 {id:"kitchen",short:"Kitchen & wintergarten",title:"Kitchen & wintergarten",summary:"Everyday life, extended into the garden.",image:"/assets/IMG_1444.jpg",alt:"The existing kitchen with sage cabinetry and a central island",intentTitle:"Make the garden the gathering place.",intent:"Use the full L-shaped wintergarten footprint shown in the exposé, extending both north and west around the kitchen. Around 40 m² of new space should make cooking, dining and everyday life more generous all year round.",photos:["IMG_1444","IMG_1448","IMG_1449","IMG_1439","IMG_1621","IMG_1622"]},
 {id:"front",short:"Front wall & arrival",title:"A new sense of arrival",summary:"A quieter, more confident boundary.",image:"/assets/IMG_1627.jpg",alt:"The current front boundary wall and gates seen from the road",intentTitle:"The house’s timber language, continued.",intent:"Replace the old roadside wall with a substantially taller boundary clad throughout in narrow horizontal timber strips that echo the house. Flush timber gates, restrained lighting and crisp detailing make privacy feel like part of the architecture.",photos:["IMG_1625","IMG_1627","IMG_1388","IMG_1393","IMG_1628"]}
];
projects.push(
 {id:'terrace',short:'East dining terrace',title:'Dining in the landscape',summary:'A generous table, open sky, and long views.',image:'/assets/IMG_1405.jpg',alt:'The existing east garden and terrace beside the house',intentTitle:'Give outdoor dining room to breathe.',intent:'Extend the east-facing terrace to create a beautiful, comfortable outdoor table area. Keep the connection from kitchen and dining room simple, and let natural stone, timber furniture and the garden do the work.',photos:['IMG_1403','IMG_1405','IMG_1407','IMG_1472','IMG_1473','IMG_1469']},
 {id:'courtyard',short:'Courtyard patio',title:'The sheltered courtyard',summary:'Find a new way to live in this in-between space.',image:'/assets/IMG_1563.jpg',alt:'The existing covered courtyard patio with timber cladding and seating',intentTitle:'A sheltered outdoor room.',intent:'Explore the covered patio in the courtyard behind the pool. Begin with different ways of using the space: a calm outdoor lounge, a sociable dining room, or a flexible combination. Work with the existing roof, posts and enclosing buildings while discovering what feels possible.',photos:['IMG_1563','IMG_1567','IMG_1561']}
);
export type Project=typeof projects[number];
export type ConceptView={id:string;title:string;image:string;source:string;category:'Inside'|'Outside';cameraKind:string;description:string};
export type Concept={views?:ConceptView[];archived?:boolean;id:string;title:string;subtitle:string;image:string;source:string;description:string;medium?:'plan';plan?:string;model?:string;layout?:'courtyard-focused'|'courtyard-isometric'|'winter-full'|'courtyard-A'|'courtyard-B'|'courtyard-C';comparison?:'spatial';imageFit?:'contain'};
export const concepts:Record<string,Concept[]>={
 east:[{id:'east-exterior',title:'The open horizon',subtitle:'East elevation · exterior study',image:'/assets/east-glazing-concept.png',source:'/assets/IMG_1403.jpg',description:'Near-continuous glazing beneath the existing timber eaves. Slender frames hold the long horizontal line, opening the bedroom, bathroom, dining and living spaces to the garden.'},{id:'east-corner',title:'Around the corner',subtitle:'Family room · interior study',image:'/assets/family-room-glass-corner-concept.png',source:'/assets/IMG_1469.jpg',description:'Full-height glass turns the corner toward the pool. The design intent is to continue the opening along the south wall to the retained fireplace; that junction is beyond this photograph.'}],
 kitchen:[
  {archived:true,id:'kitchen-west-table-v3',title:'A long table in the garden',subtitle:'01 · freestanding dining',image:'/assets/kitchen-west-table.svg',source:'/assets/kitchen-confirmed-footprint.svg',medium:'plan',imageFit:'contain',layout:'winter-full',comparison:'spatial',description:'Give the west wing to a freestanding table with individual chairs. Keep a route along the kitchen side and a small sitting area in the north return. Retain the cooker wall and island while reclaiming the old breakfast nook for preparation and storage. The drawing tests eight seats; actual furniture dimensions and clearances still need checking.'},
  {archived:true,id:'kitchen-west-banquette-v3',title:'The everyday garden room',subtitle:'02 · west-side banquette',image:'/assets/kitchen-west-banquette.svg',source:'/assets/kitchen-confirmed-footprint.svg',medium:'plan',imageFit:'contain',layout:'winter-full',comparison:'spatial',description:'A long upholstered banquette along the west glazing makes dining feel more relaxed, with a smaller table and loose chairs facing it. A reading bench uses the shallow north return. The cooker, island, outline and source openings stay in the same positions as study 01. Test upholstery height, access to glazing and furniture fit before developing an interior view.'}
 ],
 front:[{id:'front-boundary',title:'A considered arrival',subtitle:'Roadside boundary · exterior study',image:'/assets/front-boundary-concept.png',source:'/assets/IMG_1627.jpg',description:'A continuous mineral wall with flush, dark timber gates makes a calmer edge to the road. Additional height brings privacy without competing with the house. The illustrated height is a design idea, not a measured or approved dimension.'}]
};
export const briefs:Record<string,string>={
 east:'Create floor-to-ceiling glazing along the full ground-floor east façade, including the bedroom, bathroom, dining room and family room. Wrap the glazing onto the south side of the family room as far as the existing fireplace, which must remain. Maximise the sense of connection with garden, pool and distant landscape. Preserve the roofline and original architectural character. Explore slender dark bronze or black frames, timber reveals, large sliding openings and discreet privacy solutions in the bedroom and bathroom.',
 kitchen:kitchenVolumeBrief,
 front:'Completely redesign the boundary between the driveway and road as a substantially taller privacy wall. Clad the entire visible boundary and flush gates in narrow horizontal timber siding strips, matching the rhythm, warm colour and natural character of the house’s exterior. The previous mineral-wall direction is superseded. Explore continuous horizontal joints, fine shadow gaps, a slim dark cap and discreet integrated lighting, house number and intercom. Keep vehicle and pedestrian access practical. Illustrated height is a design intention; establish the final height through a measured elevation and approval review.'
};
export const designQuestions:Record<string,string[]>={
 east:['How far can the glazing run with slender structural supports?','How should sliding panels open to the garden and pool?','Can bedroom and bathroom privacy be controlled without losing the view?','How do we relocate ground-floor wall heating where solid walls disappear?','How should the glass meet the retained fireplace, floor and roof?'],
 kitchen:['How do we use the complete west and north wings as one connected space?','Where should the kitchen work zones and dining table sit?','Keep and adapt the current cabinetry, or redesign it around the larger space?','Solid insulated roof, glazed roof, or a carefully balanced combination?','How can shading, ventilation and heating make the room comfortable all year?','Does the approved drawing support the preferred layout and openings?'],
 front:['How much of the house should remain visible from the road?','Which timber tone and strip spacing best match the house’s siding?','How tall should the continuous timber boundary be to screen the driveway?','How should gates, intercom, lighting and bins be integrated?']
};
export const plans=[
 {id:'grounds',title:'House & grounds',image:'/assets/grounds.png',page:18,printed:'34–35',scale:'1:300'},
 {id:'ground-floor',title:'Ground floor',image:'/assets/ground-floor.png',page:19,printed:'36–37',scale:'1:125'},
 {id:'upper-floor',title:'Upper floor',image:'/assets/upper-floor.png',page:20,printed:'38–39',scale:'1:125'},
 {id:'basement',title:'Basement',image:'/assets/basement.png',page:21,printed:'40–41',scale:'1:125'},
 {id:'location',title:'Site location',image:'/assets/location.png',page:17,printed:'32–33',scale:'1:1000'}
];
export const photoLabels:Record<string,string>={IMG_1403:'East façade from the garden',IMG_1405:'Garden, house and pool',IMG_1407:'The house from the meadow',IMG_1444:'Kitchen and central island',IMG_1448:'La Cornue range detail',IMG_1449:'Range and kitchen finishes',IMG_1469:'Family room — east and south corner',IMG_1467:'Family room toward the pool',IMG_1462:'Family room and fireplace',IMG_1451:'Ground-floor bedroom',IMG_1454:'Ground-floor bathroom',IMG_1627:'Roadside wall and gates',IMG_1625:'Arrival from the road',IMG_1472:'Dining room',IMG_1473:'Dining room toward the garden',IMG_1388:'Approach to the house',IMG_1439:'Entrance and garage wing',IMG_1563:'Covered terrace',IMG_1579:'Pool-side gable',IMG_1622:'Front garden and façade'};

briefs.terrace='Extend the east-facing terrace to create a generous, beautiful outdoor dining area with a comfortable full-size table. Start by testing 8–10 seats as a design assumption. Allow space to move behind occupied chairs and maintain easy circulation from the house and toward the pool. Continue the natural materials of the house with compatible stone paving and timber furniture. Explore light, flexible shading that does not compromise the garden views. Coordinate the terrace level, drainage and threshold with the proposed east glazing.';
briefs.courtyard='Reimagine the covered patio in the courtyard behind the pool. This is an open exploration: compare a restful lounge, a dining and entertaining space, and a flexible combination. Preserve the character of the timber-clad buildings and use natural materials. Initially retain the existing roof and structural posts; any larger structural changes require separate feasibility work. Improve comfort, furniture layout, lighting and connection to the pool. Seek inspiration before fixing the programme.';
designQuestions.terrace=['What table size and number of seats feels right?','Where should the enlarged terrace sit relative to dining-room doors and pool circulation?','Can paving and floor levels read as one continuous surface?','Parasol, retractable shade, or a light pergola?','How should the edge meet the lawn, planting and drainage?'];
designQuestions.courtyard=['Would you spend more time here lounging, dining, or both?','What makes the current patio feel underused or awkward?','Can furniture, lighting and finishes transform it without structural changes?','Would a discreet serving counter or outdoor kitchen add value?','How can the courtyard connect more naturally to the pool?'];
concepts.terrace=[{id:'terrace-table',title:'A table in the landscape',subtitle:'East terrace · outdoor dining study',image:'/assets/terrace-dining-concept.png',source:'/assets/IMG_1403.jpg',description:'A generous stone terrace projects into the garden beside the dining and family-room doors. A timber table, comfortable chairs and a simple parasol keep the composition relaxed. The terrace footprint and seating clearances remain to be measured.'}];
concepts.courtyard=[{id:'courtyard-lounge',title:'The quiet outdoor room',subtitle:'Courtyard · lounge direction',image:'/assets/courtyard-lounge-concept.png',source:'/assets/IMG_1567.jpg',description:'Built-in timber seating, a stone coffee table and soft indirect light turn the covered loggia into a place to linger. This first direction keeps the roof and posts. The existing outdoor fireplace in the adjoining courtyard bay stays part of the wider brief.'},{id:'courtyard-dining',title:'Gather under the eaves',subtitle:'Courtyard · dining direction',image:'/assets/courtyard-dining-concept.png',source:'/assets/IMG_1567.jpg',description:'A long table and a discreet serving counter create a sheltered place for slow lunches and evening meals, with a small lounge at the end. Compare this sociable direction with the quieter lounge. It uses the existing enclosure; furniture fit and fireplace circulation need a measured plan.'}];
briefs.courtyard+=' Compare three layouts across the whole L: A, a fireplace lounge with dining in the perpendicular bay; B, dining beside the fireplace with a separate pool-facing lounge; C, a garden salon with several smaller seating areas and a daybed, leaving formal dining to the east terrace. Keep circulation between the house, pool and both covered bays clear. The newer photographs reveal an existing outdoor fireplace and the full L-shaped courtyard. Retain that fireplace as a design anchor unless a later study explicitly proposes otherwise.';
designQuestions.courtyard.push('How can the existing outdoor fireplace anchor the wider L-shaped courtyard?');

// Second-round studies respond to the owner’s room, footprint and layout feedback.
concepts.east.push(
 {id:'east-fireplace-view-v2',title:'Glass to the fireplace',subtitle:'Family room · looking out',image:'/assets/family-room-fireplace-glazing-v2.png',source:'/assets/IMG_1462.jpg',description:'The garden wraps around the seating area through full-height east and south glazing, ending at the retained fireplace. Slim dark frames and timber reveals keep the warmth of the original room.'},
 {id:'east-bedroom-view-v2',title:'Wake up in the landscape',subtitle:'Ground-floor bedroom · looking out',image:'/assets/bedroom-garden-glazing-v2.png',source:'/assets/IMG_1451.jpg',description:'A wider, calmer glass wall brings the meadow into the bedroom. The existing four-poster and oak floor stay; curtains drawn fully aside preserve the view and close for privacy when needed.'}
);

concepts.east.push({id:'east-bathroom-view-v2',title:'A bath beside the garden',subtitle:'Ground-floor bathroom · looking out',image:'/assets/bathroom-private-garden-glazing-v2.png',source:'/assets/IMG_1454.jpg',imageFit:'contain',description:'Refined full-height glazing gives the bath a direct connection to the garden. A translucent lower band tests one privacy approach, with clear glass above and linen curtains at the edges. The bath and brass fittings remain; privacy from outside needs to be tested at seated and standing eye levels.'});
// The previous mineral-wall image stays in the asset archive; this is the active direction.
concepts.front=[{id:'front-horizontal-timber-v2',title:'One continuous timber edge',subtitle:'Taller roadside boundary · revised direction',image:'/assets/front-boundary-horizontal-timber-v2.png',source:'/assets/IMG_1627.jpg',description:'A substantially taller privacy boundary, wrapped throughout in narrow horizontal timber strips. The wall, pedestrian gate and driveway gate share the house’s warm timber palette, with aligned joints and slim dark detailing. This replaces the earlier mineral-wall direction. Height is illustrative, not a measured or approved dimension.'}];
concepts.courtyard.unshift(
 {id:'courtyard-layout-A-v2',title:'A · Lounge by the fire',subtitle:'Whole courtyard · lounge + long-table dining',image:'/assets/courtyard-fireplace-lounge-longtable-v2.png',source:'/assets/FDE39D63-B192-4A7E-A16B-886A2F38F0A6_1_105_c.jpg',layout:'courtyard-A',comparison:'spatial',description:'An intimate lounge gathers around the existing outdoor fireplace, while the perpendicular covered bay becomes a long-table dining room. Both activities look onto the open lawn and tree. The intention is to furnish the existing structure; the render’s post and fireplace positions are approximate.'},
 {id:'courtyard-layout-B-v2',title:'B · Dine by the fire',subtitle:'Whole courtyard · dining + pool-facing lounge',image:'/assets/courtyard-fireplace-dining-poolsofa-v2.png',source:'/assets/FDE39D63-B192-4A7E-A16B-886A2F38F0A6_1_105_c.jpg',layout:'courtyard-B',comparison:'spatial',description:'Exchange the two uses: put dining and a serving console near the fireplace, then give the other bay to a relaxed sofa group looking toward the courtyard and pool. A freestanding sofa is the layout ambition; this render keeps it closer to the wall. Preserve the existing roof and posts, with furniture clearances checked on a measured plan.'},
 {id:'courtyard-layout-C-v2',title:'C · The garden salon',subtitle:'Whole courtyard · conversation + reading + daybed',image:'/assets/courtyard-garden-salon-daybed-v2.png',source:'/assets/FDE39D63-B192-4A7E-A16B-886A2F38F0A6_1_105_c.jpg',layout:'courtyard-C',comparison:'spatial',description:'Smaller conversation groups share the fireplace bay, with a reading chair and daybed in the perpendicular bay. Keep the centre open and let this be a place to slow down, with formal outdoor dining on the east terrace. No long dining table in this arrangement.'}
);

const tagProject:Record<string,string>={'east-glazing':'east','kitchen':'kitchen','roadside-wall':'front','east-dining-terrace':'terrace','covered-courtyard':'courtyard'};
for(const [id,data] of Object.entries(newCatalog)){
 photoLabels[id]=data.title;
 for(const tag of data.tags){const p=projects.find(p=>p.id===tagProject[tag]);if(p&&!p.photos.includes(id))p.photos.push(id);}
}

concepts.kitchen.unshift(...kitchenVolumeConcepts);

// Third-round courtyard studies combine all three requested uses.
concepts.courtyard= [...courtyardIsometricConcepts,...concepts.courtyard.map(c=>({...c,archived:true}))];
briefs.courtyard="Explore the whole courtyard behind the pool with an eating area, a lounge with two daybeds and cozy seats in every layout. Keep the existing L-shaped arrangement, including the long slightly angled west wing, the shallow north loggia, and its uncovered front terrace. Retain the roof, posts, existing outdoor fireplace, timber character, tree and pool. Compare three source-based isometric studies: A, a generous banquette table at the north terrace with west-wing daybeds and fireside chairs; B, two north-bay daybeds with a round outdoor dining table in front and cozy fireside chairs; C, a compact dining nook and separate sofa in the north bay, plus west-wing daybeds and fireside chairs. Use natural timber furniture, soft oatmeal and sage fabrics and restrained stone details. Keep routes to the house, adjoining rooms and pool practical. The isometric illustrations omit the existing roof only to reveal the arrangement; this is not a roof-removal or pergola proposal. The source-plan outline governs the layout. Furniture, tree position, glazed opening details and heights remain indicative; verify door swings, chair pull-out space, rain coverage and fit with a survey. Earlier concepts remain available in the archive.";
designQuestions.courtyard=['Which balance feels best: a larger dining table, paired daybeds under cover, or several smaller places to sit?', 'Should dining stay sheltered, or can some seats sit on the open terrace?', 'How can daybeds and cozy seats keep room doors and the route to the pool clear?', 'What furniture sizes fit between the existing timber posts?', 'How should cushions, lighting and textiles make the space inviting through the seasons?'];

// The chosen directions stay first; saved favorites keep their existing identifiers.
concepts.kitchen=[gardenKitchen,...concepts.kitchen.map(c=>({...c,archived:true,...(c.id==='kitchen-abc-social'?{description:'Superseded Social kitchen study. The north sofa and earlier joinery have been replaced. Earlier exterior renders contain inconsistent furniture orientation; use the current plan for geometry.',views:c.views?.map(v=>({...v,description:(v.category==='Outside'?'Superseded: furniture orientation is unreliable in this exterior image. ':'')+v.description}))}:{})}))];
concepts.courtyard=[firesideCourtyard,...concepts.courtyard.filter(c=>c.id!==firesideCourtyard.id).map(c=>({...c,archived:true}))];
briefs.kitchen=gardenKitchenBrief;
briefs.courtyard=firesideCourtyardBrief;
designQuestions.kitchen=['Does the wider cooking aisle work with an open oven or dishwasher?', 'Is the north breakfast bar the right balance of casual seating and storage?', 'Would a raised second oven be worth trading some pantry space?', 'How can external shading preserve the glass-wrapped dining atmosphere?', 'Which roof, use and structural details are already in the stamped approval?'];
designQuestions.courtyard=['How long can the dining table be while leaving room to pull out chairs?', 'What should the wall counter store, and where should it stop for doors?', 'Which sofa and cozy chair sizes fit around the existing fire?', 'How can lighting connect the two bays without competing with the garden?'];

concepts.east.unshift({id:'east-dining-window-1457-v1',title:'A table by the glass',subtitle:'Family room · dining at the garden end',image:'/assets/east-dining-window-1457-v1.webp',source:'/assets/IMG_1457.jpg',comparison:'spatial',imageFit:'contain',description:'A six-seat oak dining table takes the place of the far sofa and the people in IMG_1457, its long edge running almost horizontally across the view. Full-height glazing opens the east wall and wraps around the corner to the retained fireplace. The foreground sofa keeps a distinct lounge area, while slender dark frames and warm timber reveals continue the other east façade studies. Compare shows the original photograph beside the render; furniture clearances and structural details remain to be checked.'});

projects.push({id:'solar',short:'Solar & battery storage',title:'A quieter kind of power',summary:'Electricity for the house and two cars. Gas heating stays.',image:'/assets/IMG_1403.jpg',alt:'The east roof before solar panels',intentTitle:'A smaller array. The same quiet roofline.',intent:'Keep the gas heating system and cover existing electricity plus two Tesla Model Ys travelling 5,000 km each per year. Compare annual electricity balance with winter grid independence, using hourly site weather and clearly stated demand assumptions.',photos:['IMG_1403','IMG_1405','C106337F-A37F-4ABC-99D4-17206D0F5444_1_105_c','DC2E6390-D8F3-4212-A5DB-8EB9AE083A93_1_105_c','F92D9025-5B99-4FAF-9BAE-ECC47E3D555A_1_105_c']});
concepts.solar=[
 {id:'solar-east-v2',title:'Quiet power, above the garden',subtitle:'Current proposal · main east roof · 26 panels',image:'/assets/solar-main-east-v2.webp',source:'/assets/IMG_1403.jpg',comparison:'spatial',imageFit:'contain',description:'Updated photo visualization for the 50-panel proposal: 26 modules allocated to the main east roof, with 24 on the opposite main roof and none on the guest wing. Dark, low-profile panels sit around the retained roof windows. The original trees and roofline stay. Use the counted diagram and 3D view for the panel schedule; photographic perspective, foliage and AI detail limit exact counting in this image.'},
 {id:'solar-west-v2',title:'A quiet roof above the kitchen',subtitle:'Current proposal · main west roof · 24 panels',image:'/assets/solar-main-west-v2.webp',source:'/assets/C106337F-A37F-4ABC-99D4-17206D0F5444_1_105_c.jpg',comparison:'spatial',imageFit:'contain',description:'The kitchen-side main roof carries the other 24 planned modules. The pine naturally conceals part of this roof; visible panels are only a partial view of the array. The guest wing and connecting roof remain free of panels. Existing roof windows, including the high window in this reference, are retained. The photograph reveals details not resolved by the simplified roof model, so final module positions need a measured roof survey.'},
 {id:'solar-counted-layout',title:'Every panel, accounted for',subtitle:'Current gas-retained scenario · 50 panels',image:'/assets/solar-roof-layout.svg',source:'/assets/upper-floor.png',medium:'plan',imageFit:'contain',description:'50 landscape modules, each 1.722 × 1.134 m and 450 W: main east 26, main west 24, guest wing none. Total 22.5 kWp / 97.6 m², producing approximately 17.4 MWh/year against estimated electricity demand of 15.6 MWh. This is the arrangement used in the 3D layer, with two battery placeholders. The guest roof is left untouched. Annual balance still relies on winter grid imports. The simplified model must be reconciled with all photographed roof windows, installation clearances, shading and structure during survey.'},
 {archived:true,id:'solar-east-v1',title:'Earlier east-roof study',subtitle:'Archived · earlier rendering',image:'/assets/solar-main-east-v1.webp',source:'/assets/IMG_1403.jpg',comparison:'spatial',imageFit:'contain',description:'Superseded by the current main-east photo visualization. Kept for comparison with the original larger roof study.'},
 {archived:true,id:'solar-guest-v1',title:'Earlier guest-wing panels',subtitle:'Archived · not in the current proposal',image:'/assets/solar-guest-west-v1.webp',source:'/assets/DC2E6390-D8F3-4212-A5DB-8EB9AE083A93_1_105_c.jpg',comparison:'spatial',imageFit:'contain',description:'Earlier appearance reference for the 117-panel array. These guest-wing panels are not part of the current 50-panel proposal. The guest roof stays unchanged.'}
];
briefs.solar='Keep the existing gas heating system. Size PV for current electricity plus two Tesla Model Ys travelling 5,000 km each annually, assuming 20 kWh/100 km at the charger and all charging at home. Working electricity demand: 15,611 kWh/year, inferred from the €412 monthly electricity advance using €0.35/kWh and €180/year standing charges, plus 2,000 kWh for both cars. Actual kWh are unverified. No heat-pump conversion, new electric pool/wintergarten heating or additional cooling loads are included. The revised 50-panel main-roof study is 22.5 kWp / 97.6 m², yielding about 17.4 MWh/year; main east 26, main west 24. Average annual balance before battery losses is about 45 panel-equivalents / 20.25 kWp / 87.9 m² at this orientation mix. Two 13.5 kWh storage units achieve approximately 71% hourly solar supply in the model, importing about 4.6 MWh/year; four units about 75%. The original 117-panel roof capacity comparison gives about 86% with two and 92% with four, but remains short of winter electricity independence. Gas is still required. Preserve the rooflines, skylights, trees and architectural calm. Confirm metered electricity, existing EV consumption, winter shading, roof geometry, peak demand, phases, inverter capacity and installation clearances before selecting equipment.';
designQuestions.solar=['What are the actual annual electricity kWh behind the €412 monthly advance?','Does the existing electricity use already include EV charging?','Can the cars charge from surplus solar during the day?','How much winter shade do the trees cast on the main roof?','Would the smaller array plus two batteries feel sufficient, or is the larger roof worth exploring for less grid reliance?','Which certified inverter and battery arrangement meets the desired household and car-charging backup loads?'];
