import {socialKitchenViews} from './social-kitchen-views';
import type {Concept} from './design-data';
const base={source:'/assets/IMG_1444.jpg',imageFit:'contain',layout:'winter-full',comparison:'spatial'} as const;
export const kitchenVolumeConcepts:Concept[]=[
 {...base,id:'kitchen-abc-social',title:'The social kitchen',subtitle:'A + B + C · cooking at the centre',image:socialKitchenViews[0].image,views:socialKitchenViews,plan:'/assets/kitchen-abc-social-plan.svg',model:'/assets/kitchen-abc-social-model.svg',description:'Open the west and north connections so the enlarged kitchen in C, garden table in A and morning lounge in B share one space. A larger, shifted island and extra preparation storage make C work harder; the cooker stays on the east wall. The plan tests eight dining seats. Wider openings and retained supports are proposals for structural review.'},
 {...base,archived:true,id:'kitchen-abc-garden',title:'Cook in the garden',subtitle:'A + B + C · a new place to cook',image:'/assets/kitchen-abc-garden-concept.png',plan:'/assets/kitchen-abc-garden-plan.svg',model:'/assets/kitchen-abc-garden-model.svg',description:'Move the working kitchen into A, with low counters at the west glazing and a parallel island. C becomes the main dining room with a generous serving wall; B is a breakfast and coffee corner. This relocates the cooker and sink, needs new services and extraction, and opens both old room boundaries. The illustration adds island stools; their fit is not established in the plan.'},
 {...base,archived:true,id:'kitchen-abc-family',title:'The all-day family room',subtitle:'A + B + C · somewhere to stay all day',image:'/assets/kitchen-abc-family-concept.png',plan:'/assets/kitchen-abc-family-plan.svg',model:'/assets/kitchen-abc-family-model.svg',description:'Give A to a proper sofa and armchair, place a six-seat dining table at the northwest corner across A and B, and redesign C around perimeter cabinetry and a freestanding island. Keep the cooker east and add a quiet reading bench in the north return. Both old room boundaries open up around retained supports. Furniture fit and structure remain to be checked.'}
];
export const kitchenVolumeBrief='Develop the selected Social kitchen across the full confirmed A+B+C volume. A is the long WEST extension with an eight-seat dining table running north–south. B is the shallow NORTH return with one sofa and a coffee table. C is the enlarged original kitchen with a generous freestanding oak island running north–south; D, the cooker, stays on its EAST wall. Open the former west and north boundaries around retained piers as a structural proposal. Keep the confirmed outline and proportions: do not rotate, mirror, deepen B or enlarge the envelope. Use the Social kitchen plan and fixed spatial model to control geometry. Explore pale oak, limestone, sage range cabinetry, slim dark glazing and a low insulated extension roof with oak soffits; retain the original white kitchen ceiling. Use the original interior and garden photographs for views and distinguish photo-based views from inferred new viewpoints. AI images convey atmosphere and finishes; they do not establish dimensions, roof or structure. The alternative layouts remain in the archive. Furniture fit, openings, ceiling heights, services and the actual approved drawings remain to be verified.';
