import photos from '../photos.json';
import type {Level} from './site-data';
export type InteriorRoom={id:string;label:string;level:Level;center:[number,number];span:number;detail:string;note?:string;photos:string[]};
const refs=(...indices:number[])=>indices.map(i=>photos[i].src);
export const interiorRooms:InteriorRoom[]=[
 {id:'kitchen',label:'Kitchen & breakfast corner',level:'ground',center:[880,320],span:9,detail:'Sage cabinetry, timber worktops, sink island and black range. The north end has an L-shaped breakfast bench and white chairs. A full-height sliding door leads to the long outdoor table on the west terrace.',photos:refs(9,10,169)},
 {id:'dining',label:'Dining alcove',level:'ground',center:[1130,582],span:7,detail:'A timber U-shaped banquette with grey cushions wraps the table. Three white chairs sit on the open side.',photos:refs(15,21,119)},
 {id:'living',label:'Family room',level:'ground',center:[1020,778],span:10,detail:'Two cream sofas face one another across a glass coffee table, with the fireplace on the south wall and a woven chair beside the garden.',photos:refs(14,17,19)},
 {id:'bedroom',label:'Garden bedroom',level:'ground',center:[1100,286],span:8,detail:'The timber four-poster, stump bedside tables, framed wardrobes and patterned rug identify the existing bedroom.',photos:refs(12,123)},
 {id:'bath',label:'Garden bathroom',level:'ground',center:[1150,453],span:7,detail:'An oval freestanding bath beside the east glazing and two white basins on a timber console with a black frame.',photos:refs(13,80,90)},
 {id:'main-atrium',label:'Main hall & open staircase',level:'ground',center:[960,565],span:9,detail:'Open timber treads and black steel railings rise through the double-height hall. The connecting corridor opens through the small entrance hall, with the WC behind the staircase on your left.',photos:refs(24,44,105)},
 {id:'hall-wc',label:'Hallway bathroom',level:'ground',center:[857,570],span:5,detail:'The small WC behind the main staircase, entered from the hallway that connects the two wings. The toilet and basin follow the exposé plan.',note:'Location confirmed by the owner. Fixtures are traced from the plan; their finishes are approximate.',photos:['/assets/ground-floor.png']},
 {id:'entry',label:'Entrance & garage',level:'ground',center:[449,622],span:18,detail:'A stone walkway reaches the front door. The glazed entrance has a stone floor and a pine cupboard bank that stops before the courtyard doorway. The garage has two timber vehicle doors, a door into the connecting corridor and two illustrative Model Ys.',photos:refs(7,42,97)},
 {id:'yoga',label:'Guest wing · yoga room',level:'ground',center:[252,865],span:7,detail:'An open timber floor with a yoga mat and bolster, separated from the wall-hugging, quarter-turn staircase by a partition and doorway.',photos:refs(54,148)},
 {id:'wellness',label:'Guest wing · wellness',level:'ground',center:[204,1104],span:9,detail:'Rust lounge modules, a low dark table and a corner sauna with timber lining, stepped benches, a glazed front and a stone-filled heater.',photos:refs(51,52,78)},
 {id:'north-bedroom',label:'Upper · four-poster room',level:'upper',center:[986,293],span:8,detail:'A timber four-poster against the central dividing wall, worktop with white drawers and black desk chair. The south wall separates the bedroom from the gallery, with a doorway beside the bathroom.',note:'The two mirrored north bedrooms are confirmed by the owner; the second room uses this room’s furniture as its reference.',photos:refs(25,26,143)},
 {id:'northeast-bedroom',label:'Upper · northeast bedroom',level:'upper',center:[1150,295],span:8,detail:'The northwest room mirrored, with the four-poster bed brought against the dividing wall, a long desk.',note:'Mirrored arrangement confirmed by the owner; these photographs show the matching northwest room.',photos:refs(25,26,143)},
 {id:'north-bathroom',label:'Upper · shared bedroom bathroom',level:'upper',center:[1064,345],span:7,detail:'A door from each north bedroom leads to its own vanity. The central partition separates the two sides and stops before one shared shower area along the north wall.',note:'Layout follows your annotated correction and the exposé. Door widths, fittings and finishes remain approximate.',photos:['/assets/upper-floor.png']},
 {id:'main-gallery',label:'Upper · open atrium & gallery',level:'upper',center:[1030,550],span:11,detail:'The full double-height opening beside the stair, with slim black railings and open circulation between the gallery and dressing area.',photos:refs(102,151,156)},
 {id:'upper-bedroom',label:'Upper · south bedroom',level:'upper',center:[1125,765],span:7,detail:'A low bed, large pink rug and a television on a slim black stand opposite.',note:'Position is interpreted from the gable door and roof slope; dimensions remain approximate.',photos:refs(28,106)},
 {id:'upper-bath',label:'Upper · south bathroom',level:'upper',center:[975,765],span:7,detail:'The freestanding bath sits under the slope opposite a timber console with two white basins. A separate toilet room and shower sit along the atrium wall, and the bedroom doorway is wider.',photos:refs(29,30,31)},
 {id:'gallery-bathroom',label:'Upper · gallery bathroom',level:'upper',center:[1190,449],span:5,detail:'The small enclosed bathroom off the east gallery contains a toilet and a single vanity, with its doorway facing the gallery.',note:'Position and fixtures follow your correction and the original upper-floor plan. Dimensions and finishes remain approximate.',photos:['/assets/upper-floor.png']},
 {id:'study',label:'Guest upper · study',level:'upper',center:[306,663],span:8,detail:'A long cushioned timber daybed tucked against the west side, a worktop under the opposite slope and a black-and-white patterned rug.',photos:refs(59,133,147)},
 {id:'gallery',label:'Guest upper · kitchenette',level:'upper',center:[276,868],span:7,detail:'White cabinets with a timber worktop, black sink fittings and a red bistro table beside the open stair atrium and black horizontal railing. The stair turns onto a landing through an opening beside the kitchenette.',photos:refs(57,58,180)},
 {id:'guest-bedroom',label:'Guest upper · bedroom',level:'upper',center:[282,1101],span:8,detail:'A cream double bed tucked toward the far corner, stump tables and a separate small washbasin in the corner beside the entrance.',photos:refs(60,61,118)},
 {id:'guest-upper-bath',label:'Guest upper · shower & WC',level:'upper',center:[232,988],span:6,detail:'An enclosed bathroom with a toilet at the north end, shower at the south end and a doorway facing the bedroom. The separate vanity sits outside by the entrance.',note:'Enclosure and fixtures follow the exposé and your annotated correction; dimensions and finishes remain approximate.',photos:['/assets/upper-floor.png']},
 {id:'wine',label:'Basement · wine cellar',level:'basement',center:[877,558],span:8,detail:'Timber bottle racks fill the narrow wine room beside the stair.',photos:refs(36,37,139)},
 {id:'laundry',label:'Basement · laundry',level:'basement',center:[1145,557],span:8,detail:'Dark blue cabinets, a timber worktop and four white front-loading appliances in the room labelled HWR on the plan.',photos:refs(74,152,173)},
 {id:'hobby',label:'Basement · hobby room',level:'basement',center:[1030,767],span:10,detail:'A mostly open space with a worktable, dark chairs, wall storage and a yoga mat.',photos:refs(34,35,182)}
];
