import * as T from 'three';
import {addShaderFeature,after,before,materialsOf} from './shader-features';

/** Tileable surface sets generated by scripts/build-materials.mjs. Surfaces are projected
 * in world space, so merged and scaled geometry needs no UVs and tiles at true size. */
export type Surface='cladding'|'roof'|'oak'|'stone'|'lawn'|'deck'|'linen'|'plaster';
const metres:Record<Surface,[number,number]>={cladding:[1.2,1.2],roof:[1.2,1.2],oak:[1.32,1.32],stone:[1.2,1.2],lawn:[2,2],deck:[.9,.9],linen:[.08,.08],plaster:[2,2]};
const onlySmall=new Set<string>(['linen','plaster','bark']);
/** The colour each set was painted at; materials keep their own shade relative to it. */
const painted:Record<Surface,string>={cladding:'#6e5946',roof:'#4d5453',oak:'#c6aa80',stone:'#cfccc0',lawn:'#a0b18d',deck:'#8c867b',linen:'#e7e0cc',plaster:'#e9e4d9'};
const bump:Record<Surface,number>={cladding:1,roof:.9,oak:.7,stone:.6,lawn:1,deck:.8,linen:.5,plaster:.5};
export const surfaceUrl=(name:string,size:number,kind:'color'|'normal')=>`/assets/materials/${name}-${onlySmall.has(name)?512:size}-${kind}.webp`;

export type SurfaceTextures={size:number;get:(name:string)=>{color:T.Texture;normal:T.Texture};water:T.Texture;ready:Promise<void>;dispose:()=>void};
export function loadSurfaceTextures(size:512|1024,renderer:T.WebGLRenderer,onLoad:()=>void):SurfaceTextures{
 const loader=new T.TextureLoader(),cache=new Map<string,T.Texture>(),pending:Promise<unknown>[]=[];
 const anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());
 const load=(url:string,srgb:boolean)=>{
  let tex=cache.get(url);if(tex)return tex;
  tex=new T.Texture();tex.wrapS=tex.wrapT=T.RepeatWrapping;tex.anisotropy=anisotropy;if(srgb)tex.colorSpace=T.SRGBColorSpace;
  const target=tex;cache.set(url,tex);
  pending.push(loader.loadAsync(url).then(loaded=>{target.image=loaded.image;target.needsUpdate=true;loaded.dispose();onLoad();}).catch(()=>{}));
  return tex;
 };
 const water=load(`/assets/materials/water-${size}-normal.webp`,false);
 return {
  size,water,
  get:(name:string)=>({color:load(surfaceUrl(name,size,'color'),true),normal:load(surfaceUrl(name,size,'normal'),false)}),
  get ready(){return Promise.all(pending).then(()=>{});},
  dispose:()=>cache.forEach(t=>t.dispose()),
 };
}

const projection=`
vec2 surfaceUV(vec3 p,vec3 n,out vec3 tu,out vec3 tv){
 vec3 a=abs(n);
 if(uSurfaceSlope>0.5&&a.y<0.97&&a.y>0.08){tu=normalize(cross(vec3(0.0,1.0,0.0),n));tv=normalize(cross(n,tu));}
 else if(a.y>=a.x&&a.y>=a.z){tu=vec3(1.0,0.0,0.0);tv=vec3(0.0,0.0,-1.0);}
 else if(a.x>=a.z){tu=vec3(0.0,0.0,-sign(n.x));tv=vec3(0.0,1.0,0.0);}
 else{tu=vec3(sign(n.z),0.0,0.0);tv=vec3(0.0,1.0,0.0);}
 return vec2(dot(p,tu),dot(p,tv))/uSurfaceMetres;
}`;

/** World-projected albedo, roughness, relief and cavity for one surface set. */
function surfaceFeature(material:T.MeshStandardMaterial,surface:Surface,textures:SurfaceTextures){
 const set=textures.get(surface),ref=new T.Color(painted[surface]),own=material.color;
 const tint=new T.Color(T.MathUtils.clamp(own.r/ref.r,.3,2),T.MathUtils.clamp(own.g/ref.g,.3,2),T.MathUtils.clamp(own.b/ref.b,.3,2));
 const uniforms={uSurfaceColor:{value:set.color},uSurfaceNormal:{value:set.normal},uSurfaceMetres:{value:new T.Vector2(...metres[surface])},uSurfaceTint:{value:tint},uSurfaceBump:{value:bump[surface]},uSurfaceSlope:{value:surface==='roof'?1:0},uLawn:{value:surface==='lawn'?1:0}};
 material.color.set('#ffffff');material.userData.surfaceUniforms=uniforms;
 addShaderFeature(material,{key:'surface-v1',compile:shader=>{
  Object.assign(shader.uniforms,uniforms);
  shader.vertexShader='varying vec3 vSurfacePos;varying vec3 vSurfaceNormal;\n'+after(shader.vertexShader,'project_vertex',`
   vec4 surfaceWorld=vec4(transformed,1.0);vec3 surfaceN=objectNormal;
   #ifdef USE_INSTANCING
    surfaceWorld=instanceMatrix*surfaceWorld;surfaceN=mat3(instanceMatrix)*surfaceN;
   #endif
   vSurfacePos=(modelMatrix*surfaceWorld).xyz;vSurfaceNormal=normalize(mat3(modelMatrix)*surfaceN);`);
  shader.fragmentShader=`uniform sampler2D uSurfaceColor;uniform sampler2D uSurfaceNormal;uniform vec2 uSurfaceMetres;uniform vec3 uSurfaceTint;uniform float uSurfaceBump;uniform float uSurfaceSlope;uniform float uLawn;
varying vec3 vSurfacePos;varying vec3 vSurfaceNormal;${projection}\n`+shader.fragmentShader;
  shader.fragmentShader=after(shader.fragmentShader,'map_fragment',`
   vec3 surfaceTU,surfaceTV;vec3 surfaceN0=normalize(vSurfaceNormal);
   vec2 surfaceUv=surfaceUV(vSurfacePos,surfaceN0,surfaceTU,surfaceTV);
   // Gradients from world position stay continuous across projection seams at box edges.
   vec2 surfaceDx=vec2(dot(dFdx(vSurfacePos),surfaceTU),dot(dFdx(vSurfacePos),surfaceTV))/uSurfaceMetres;
   vec2 surfaceDy=vec2(dot(dFdy(vSurfacePos),surfaceTU),dot(dFdy(vSurfacePos),surfaceTV))/uSurfaceMetres;
   vec4 surfaceTexel=textureGrad(uSurfaceColor,surfaceUv,surfaceDx,surfaceDy);
   vec4 surfaceRelief=textureGrad(uSurfaceNormal,surfaceUv,surfaceDx,surfaceDy);
   vec3 surfaceAlbedo=surfaceTexel.rgb*uSurfaceTint;
   if(uLawn>0.5){
    // Broad, soft variation and mowing stripes break the tile repeat across the lawn.
    vec3 macro=texture(uSurfaceColor,vSurfacePos.xz/41.0).rgb/vec3(0.11,0.25,0.034);
    surfaceAlbedo*=mix(vec3(1.0),clamp(macro,0.7,1.3),0.55)*(1.0+0.045*sign(sin(vSurfacePos.x*2.86+vSurfacePos.z*0.35)));
   }
   diffuseColor.rgb*=surfaceAlbedo;
   float surfaceCavity=surfaceRelief.b;`);
  shader.fragmentShader=after(shader.fragmentShader,'roughnessmap_fragment','roughnessFactor=surfaceTexel.a;');
  shader.fragmentShader=after(shader.fragmentShader,'normal_fragment_maps',`
   vec2 surfaceSlopeXY=(surfaceRelief.rg*2.0-1.0)*uSurfaceBump;
   vec3 surfaceWorldN=normalize(surfaceN0*faceDirection+surfaceTU*surfaceSlopeXY.x+surfaceTV*surfaceSlopeXY.y);
   normal=normalize(mat3(viewMatrix)*surfaceWorldN);`);
  shader.fragmentShader=after(shader.fragmentShader,'aomap_fragment','reflectedLight.indirectDiffuse*=surfaceCavity;reflectedLight.indirectSpecular*=mix(1.0,surfaceCavity,0.7);');
 }});
}
/** Thin glass reflects more at glancing angles; no transmission pass, no shadow. */
export function fresnelGlass(material:T.MeshPhysicalMaterial,base=.12,tint='#e6efec'){
 Object.assign(material,{transmission:0,transparent:true,opacity:base,roughness:.03,metalness:0,depthWrite:false,envMapIntensity:1.35});
 material.color.set(tint);material.specularIntensity=1;material.side=T.DoubleSide;
 addShaderFeature(material,{key:'fresnel-glass',compile:shader=>{
  shader.fragmentShader=before(shader.fragmentShader,'opaque_fragment','diffuseColor.a=mix(diffuseColor.a,1.0,0.88*pow(1.0-abs(dot(normal,normalize(vViewPosition))),5.0));');
 }});
}
/** Pool water: tinted, reflective at glancing angles, gently rippled. */
export function poolWater(material:T.MeshStandardMaterial,normal:T.Texture,time:{value:number}){
 const physical=material as T.MeshStandardMaterial;
 Object.assign(physical,{transparent:true,opacity:.5,roughness:.035,metalness:0,depthWrite:false,envMapIntensity:1.2});
 physical.color.set('#2f8f97');
 addShaderFeature(physical,{key:'pool-water',compile:shader=>{
  shader.uniforms.uWaterNormal={value:normal};shader.uniforms.uWaterTime=time;
  shader.vertexShader='varying vec3 vWaterPos;\n'+after(shader.vertexShader,'worldpos_vertex','vWaterPos=(modelMatrix*vec4(transformed,1.0)).xyz;');
  shader.fragmentShader='uniform sampler2D uWaterNormal;uniform float uWaterTime;varying vec3 vWaterPos;\n'+shader.fragmentShader;
  shader.fragmentShader=after(shader.fragmentShader,'normal_fragment_maps',`
   vec2 w1=texture(uWaterNormal,vWaterPos.xz/2.3+vec2(uWaterTime*0.013,uWaterTime*0.007)).rg*2.0-1.0;
   vec2 w2=texture(uWaterNormal,vWaterPos.zx/3.7-vec2(uWaterTime*0.009,-uWaterTime*0.011)).rg*2.0-1.0;
   normal=normalize(mat3(viewMatrix)*normalize(vec3((w1.x+w2.y)*0.18,1.0,(w1.y+w2.x)*0.18)));`);
  shader.fragmentShader=before(shader.fragmentShader,'opaque_fragment','diffuseColor.a=mix(diffuseColor.a,1.0,0.92*pow(1.0-abs(dot(normal,normalize(vViewPosition))),4.0));');
 }});
}

/** Detailed materials: textured surfaces, clear glass, reflective water, calmer metals. */
export function finishSurfaces(root:T.Object3D,textures:SurfaceTextures,waterTime:{value:number}){
 const seen=new Set<T.Material>();
 root.traverse(o=>{
  for(const m of materialsOf(o)){
   if(seen.has(m))continue;seen.add(m);
   if(o.userData.skipSurfaces)continue;
   if(m instanceof T.MeshPhysicalMaterial&&m.transparent){if(m.roughness<.5)fresnelGlass(m,m.opacity<.3?.1:.16);continue;}
   if(!(m instanceof T.MeshStandardMaterial))continue;
   if(m.userData.water){poolWater(m,textures.water,waterTime);continue;}
   let surface=m.userData.photo as string|undefined;
   if(surface==='foliage')continue;
   // Pale, matte paints read as lime plaster; everything else keeps its flat colour.
   if(!surface&&!m.map&&m.roughness>=.7&&m.metalness<.2&&m.color.getHSL({h:0,s:0,l:0}).l>.72&&!m.emissive.getHex())surface='plaster';
   if(surface&&surface in metres)surfaceFeature(m,surface as Surface,textures);
  }
 });
 // Glass never blocks sunlight; batches may still carry the flag.
 root.traverse(o=>{if(o instanceof T.Mesh&&materialsOf(o).every(m=>m.transparent))o.castShadow=false;});
}
