import {sunDirection as modelSunDirection} from './sun-position';
import * as T from 'three';
import {terrainWithPoolOpening} from './pool';
import {landscapeContext} from './landscape-context';
import {createExperience} from './experience';
import type {ExperienceState} from './experience-data';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {Sky} from 'three/addons/objects/Sky.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {GTAOPass} from 'three/addons/postprocessing/GTAOPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {photoMaterials} from './photo-materials';
import {finishRealisticMaterials,microSurfaces} from './realism-details';
import type {TextureStatus} from './photo-sources';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import type {RenovationState} from './renovation-data';
import {buildHouseModel} from './build-model';
import {viewpoints,type Level,type Region,type Viewpoint} from './site-data';

export function createHouseViewer(host:HTMLDivElement,onSelect:(region:Region)=>void,onReady:()=>void,onError:()=>void,realistic=false,onTextures:(status:TextureStatus)=>void=()=>{},onExperience:(state:ExperienceState)=>void=()=>{}){
 const scene=new T.Scene();scene.background=new T.Color('#edece5');
 const camera=realistic?new T.PerspectiveCamera(40,1,.1,600):new T.OrthographicCamera(-35,35,25,-25,.1,450);camera.position.set(34,32,47);
 const renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio,realistic?2:1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=realistic?.82:.9;renderer.outputColorSpace=T.SRGBColorSpace;
 const canvas=renderer.domElement;canvas.setAttribute('aria-label','Interactive 3D model of Reitweg 25. Drag to orbit, pinch or scroll to zoom. Arrow keys rotate, plus and minus zoom, Home resets.');canvas.setAttribute('role','img');canvas.tabIndex=0;host.appendChild(canvas);
 const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.1;controls.minDistance=3;controls.maxDistance=240;controls.minZoom=.45;controls.maxZoom=5;controls.maxPolarAngle=Math.PI/2-.04;controls.minPolarAngle=.025;controls.target.set(-8,1,9);controls.panSpeed=.8;controls.rotateSpeed=.6;controls.autoRotateSpeed=.55;controls.zoomToCursor=true;controls.touches.ONE=T.TOUCH.ROTATE;controls.touches.TWO=T.TOUCH.DOLLY_PAN;controls.screenSpacePanning=true;controls.zoomSpeed=.85;
 let span=58,disposed=false,visible=true,dirty=60,frame=0,level:Level='exterior';
 const pmrem=new T.PMREMGenerator(renderer);let env:T.WebGLRenderTarget;
 const sunDirection=new T.Vector3(-.5,.72,.48).normalize();
 if(realistic){
  const sky=new Sky();sky.scale.setScalar(10000);const uniforms=sky.material.uniforms;
  uniforms.turbidity.value=3;uniforms.rayleigh.value=1.4;uniforms.mieCoefficient.value=.005;uniforms.sunPosition.value.copy(sunDirection);uniforms.showSunDisc.value=false;uniforms.cloudCoverage.value=.2;
  const skyScene=new T.Scene();skyScene.add(sky);env=pmrem.fromScene(skyScene,.025,.1,20000);
  sky.geometry.dispose();sky.material.dispose();scene.background=env.texture;scene.backgroundIntensity=.12;scene.backgroundBlurriness=.06;scene.fog=new T.Fog('#dce4e2',150,340);
 }else{const room=new RoomEnvironment();env=pmrem.fromScene(room,.05);room.dispose();}
 scene.environment=env.texture;scene.environmentIntensity=realistic?.12:.3;pmrem.dispose();
 const hemisphere=new T.HemisphereLight(realistic?'#eff6ff':'#fffdf1',realistic?'#806d49':'#b7bba7',realistic?.35:1.5);scene.add(hemisphere);
 const sun=new T.DirectionalLight('#fff4de',realistic?3.3:2.4);if(realistic)sun.position.copy(sunDirection).multiplyScalar(85);else sun.position.set(-25,55,25);sun.castShadow=true;sun.shadow.mapSize.set(realistic?4096:2048,realistic?4096:2048);Object.assign(sun.shadow.camera,{left:-60,right:65,top:65,bottom:-60,near:1,far:180});sun.shadow.bias=-.00015;sun.shadow.normalBias=realistic?.015:.06;sun.shadow.radius=3;scene.add(sun);
 const model=buildHouseModel(realistic);scene.add(model.root);model.setLevel('exterior');
 let experience:ReturnType<typeof createExperience>|undefined;const waterTime={value:0};
 let photos:ReturnType<typeof photoMaterials>|undefined;
 if(realistic){const materials=finishRealisticMaterials(model.root);photos=photoMaterials(materials,()=>{dirty=3;},onTextures);microSurfaces(materials,waterTime);photos.setActive(true);}
 const composer=realistic?new EffectComposer(renderer,new T.WebGLRenderTarget(1,1,{type:T.HalfFloatType,samples:4})):undefined;
 let ao:GTAOPass|undefined;
 if(composer){composer.addPass(new RenderPass(scene,camera));ao=new GTAOPass(scene,camera);ao.blendIntensity=.75;ao.updateGtaoMaterial({radius:.85,thickness:1.2,distanceExponent:1.4,samples:12});composer.addPass(ao);composer.addPass(new OutputPass());}
 const surroundings=realistic?landscapeContext():undefined;if(surroundings)model.root.add(surroundings.group);
 const stageGeometry=terrainWithPoolOpening();if(realistic){const vertices=stageGeometry.attributes.position;for(let i=0;i<vertices.count;i++){const x=vertices.getX(i);vertices.setY(i,-5*T.MathUtils.smoothstep(x,55,140));}stageGeometry.computeVertexNormals();}
 const stage=new T.Mesh(stageGeometry,new T.MeshStandardMaterial({color:realistic?'#7e914d':'#edece5',roughness:1}));stage.position.y=realistic?-.035:-.53;stage.receiveShadow=true;scene.add(stage);
 // Orientation marker follows the compass printed on the exposé, slightly west of page-up.
 const compass=new T.Group();const stem=new T.ArrowHelper(new T.Vector3(...modelSunDirection(0,0)).normalize(),new T.Vector3(37,.1,29),4,0x687963,.7,.45);compass.add(stem);scene.add(compass);
 let transition:null|{start:number;from:T.Vector3;to:T.Vector3;fromTarget:T.Vector3;toTarget:T.Vector3;fromSpan:number;toSpan:number}=null;
 const resize=()=>{if(experience?.active)experience.stop();const {width,height}=host.getBoundingClientRect();if(!width||!height)return;renderer.setSize(width,height);composer?.setSize(width,height);const aspect=width/height,framingSpan=Math.max(span,span*(level==='exterior'?(width<768?1.28:1.65):1)/aspect);if(camera instanceof T.OrthographicCamera){camera.left=-framingSpan*aspect/2;camera.right=framingSpan*aspect/2;camera.top=framingSpan/2;camera.bottom=-framingSpan/2;}else{camera.aspect=aspect;if(experience?.presenceId!=='overview'&&experience)camera.fov=65;else camera.fov=T.MathUtils.radToDeg(2*Math.atan(framingSpan/(2*camera.position.distanceTo(controls.target))));}camera.updateProjectionMatrix();dirty=30;};
 const observer=new ResizeObserver(resize);observer.observe(host);const visibility=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;if(visible)dirty=30;});visibility.observe(host);
 const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 const view=(key:Viewpoint,instant=false)=>{experience?.stop();if(experience&&experience.presenceId!=='overview'){experience.presence('overview');}const preset=viewpoints[key];const v=key==='courtyard'&&host.getBoundingClientRect().width<768?{...preset,position:[9,43,61] as [number,number,number],target:[-10,1,8] as [number,number,number]}:preset;const target=new T.Vector3(...v.target);if(level==='basement')target.y=-2;
  camera.zoom=1;transition={start:performance.now(),from:camera.position.clone(),to:new T.Vector3(...v.position),fromTarget:controls.target.clone(),toTarget:target,fromSpan:span,toSpan:v.span};if(reduced||instant){camera.position.copy(transition.to);controls.target.copy(target);span=v.span;transition=null;resize();}dirty=60;};
 const resolution=(moving:boolean)=>{if(!realistic)return;const ratio=moving?1:Math.min(window.devicePixelRatio,2);renderer.setPixelRatio(ratio);composer?.setPixelRatio(ratio);const {width,height}=host.getBoundingClientRect();renderer.setSize(width,height);composer?.setSize(width,height);dirty=5;};
 controls.addEventListener('change',()=>{dirty=3;});controls.addEventListener('start',()=>{experience?.stop();transition=null;resolution(true);dirty=30;});controls.addEventListener('end',()=>resolution(false));
 const ray=new T.Raycaster(),pointer=new T.Vector2();let press:[number,number]=[0,0];
 const down=(e:PointerEvent)=>{press=[e.clientX,e.clientY];};
 const up=(e:PointerEvent)=>{if(experience&&experience.presenceId!=='overview')return;if(Math.hypot(e.clientX-press[0],e.clientY-press[1])>5)return;const rect=canvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(model.pickables,false).find(h=>{let obj:T.Object3D|null=h.object;while(obj){if(!obj.visible)return false;obj=obj.parent;}return true;});if(hit)onSelect(hit.object.userData.region as Region);};
 const zoom=(factor:number)=>{experience?.stop();camera.zoom=T.MathUtils.clamp(camera.zoom*factor,controls.minZoom,controls.maxZoom);camera.updateProjectionMatrix();dirty=30;};
 const key=(e:KeyboardEvent)=>{if(experience&&experience.presenceId!=='overview')return;if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','Home'].includes(e.key))return;e.preventDefault();transition=null;if(e.key==='Home'){view('courtyard');return;}if(['+','=','-'].includes(e.key)){zoom(e.key==='-'?.85:1.18);return;}const offset=camera.position.clone().sub(controls.target),spherical=new T.Spherical().setFromVector3(offset);if(e.key==='ArrowLeft')spherical.theta-=.14;if(e.key==='ArrowRight')spherical.theta+=.14;if(e.key==='ArrowUp')spherical.phi-=.1;if(e.key==='ArrowDown')spherical.phi+=.1;spherical.phi=T.MathUtils.clamp(spherical.phi,.025,Math.PI/2-.04);camera.position.copy(controls.target).add(new T.Vector3().setFromSpherical(spherical));dirty=30;};
 const lost=(e:Event)=>{e.preventDefault();onError();};canvas.addEventListener('webglcontextlost',lost);canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointerup',up);canvas.addEventListener('keydown',key);
 let previous=performance.now(),ready=false,ambientCost=0;
 const render=(now:number)=>{if(disposed)return;frame=requestAnimationFrame(render);if(!visible||document.hidden){previous=now;return;}const delta=Math.min((now-previous)/1000,.05);previous=now;
  if(transition){const t=Math.min((now-transition.start)/750,1),eased=1-Math.pow(1-t,3);camera.position.lerpVectors(transition.from,transition.to,eased);controls.target.lerpVectors(transition.fromTarget,transition.toTarget,eased);span=T.MathUtils.lerp(transition.fromSpan,transition.toSpan,eased);resize();if(t===1)transition=null;}
  if(surroundings){const show=level==='exterior';if(show!==surroundings.group.visible){surroundings.group.visible=show;dirty=3;}}const changed=controls.enabled?controls.update(delta):false;const photographic=experience?.tick(now,level==='exterior',ambientCost>28?1000/15:ambientCost>18?1000/20:1000/30);if(experience)waterTime.value=experience.waterTime.value;if(!photographic&&(dirty>0||changed||controls.autoRotate||transition||experience?.motionFrame)){const renderStart=performance.now();if(dirty>0)renderer.shadowMap.needsUpdate=true;if(composer)composer.render();else renderer.render(scene,camera);const northWidget=host.parentElement?.querySelector<HTMLElement>('.model-north span');if(northWidget){const origin=controls.target.clone().project(camera),north=controls.target.clone().add(new T.Vector3(...modelSunDirection(0,0))).project(camera);const angle=Math.atan2(north.x-origin.x,north.y-origin.y)*180/Math.PI;northWidget.style.transform=`rotate(${angle}deg)`;}ambientCost=ambientCost*.9+(performance.now()-renderStart)*.1;dirty=Math.max(0,dirty-1);if(!ready){ready=true;canvas.dataset.modelReady='true';onReady();}}
 };
 if(realistic)experience=createExperience(scene,camera,renderer,controls,sun,hemisphere,model.root,()=>{dirty=3;},()=>{view('courtyard',true);},onExperience,()=>{transition=null;});
 resize();view('courtyard',true);frame=requestAnimationFrame(render);
 const focus=(x:number,z:number,y:number,framing=10)=>{camera.zoom=1;const target=new T.Vector3(x,y,z);transition={start:performance.now(),from:camera.position.clone(),to:new T.Vector3(x-8,y+12,z+10),fromTarget:controls.target.clone(),toTarget:target,fromSpan:span,toSpan:framing};if(reduced){camera.position.copy(transition.to);controls.target.copy(target);span=framing;transition=null;resize();}dirty=60;};
 const saveImage=()=>{experience?.stop();const size=renderer.getSize(new T.Vector2()),ratio=renderer.getPixelRatio(),scale=3840/Math.max(size.x,size.y);try{renderer.setPixelRatio(1);composer?.setPixelRatio(1);renderer.setSize(Math.round(size.x*scale),Math.round(size.y*scale),false);composer?.setSize(Math.round(size.x*scale),Math.round(size.y*scale));if(composer)composer.render();else renderer.render(scene,camera);const link=document.createElement('a');link.download='reitweg-25-'+(realistic?'detailed-realism':'natural-materials')+'.png';link.href=canvas.toDataURL('image/png');link.click();}finally{renderer.setPixelRatio(ratio);composer?.setPixelRatio(ratio);renderer.setSize(size.x,size.y);composer?.setSize(size.x,size.y);dirty=3;}};
 return {view,focus,zoom,saveImage,experience,snapshot:()=>({position:camera.position.toArray(),target:controls.target.toArray(),zoom:camera.zoom,span}),restore:(saved:{position:number[];target:number[];zoom:number;span:number})=>{transition=null;camera.position.fromArray(saved.position);controls.target.fromArray(saved.target);camera.zoom=saved.zoom;span=saved.span;resize();dirty=30;},setRenovations:(state:RenovationState)=>{experience?.stop();model.setRenovations(state);dirty=30;},setLevel:(l:Level)=>{experience?.stop();if(experience&&experience.presenceId!=='overview')experience.presence('overview');const floorChanged=l!==level;level=l;model.setLevel(l);stage.visible=l!=='basement';if(surroundings)surroundings.group.visible=l==='exterior';compass.visible=l!=='basement';if(floorChanged)controls.target.y=l==='basement'?-2:l==='upper'?3.1:1;resize();dirty=30;},setTrees:(show:boolean)=>{experience?.stop();model.trees.visible=show&&level==='exterior';if(surroundings)surroundings.vegetation.visible=show;dirty=30;},setRotate:(rotate:boolean)=>{experience?.stop();controls.autoRotate=rotate;dirty=30;},dispose:()=>{disposed=true;experience?.dispose();cancelAnimationFrame(frame);observer.disconnect();visibility.disconnect();controls.dispose();canvas.removeEventListener('webglcontextlost',lost);canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('keydown',key);photos?.dispose();composer?.passes.forEach(pass=>pass.dispose());composer?.dispose();model.dispose();stage.geometry.dispose();(stage.material as T.Material).dispose();env.dispose();scene.traverse(o=>{if(o instanceof T.Line||o instanceof T.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose());}});renderer.dispose();renderer.forceContextLoss();canvas.remove();}};
}
export type HouseViewer=ReturnType<typeof createHouseViewer>;
